name: gdgdoc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^8.0.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.12.1
  shimmer: ^3.0.0
  blobs: ^2.0.0
  google_fonts: ^6.2.1
  simple_animations: ^5.1.0
  simple_gradient_text: ^1.3.0
  smooth_sheets: ^0.11.0
  faker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
