name: gdgdoc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^8.0.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.12.1
  shimmer: ^3.0.0
  blobs: ^2.0.0
  google_fonts: ^6.2.1
  simple_animations: ^5.1.0
  simple_gradient_text: ^1.3.0
  percent_indicator: ^4.2.5
  smooth_sheets: ^0.11.0
  faker: ^2.2.0
  standard_searchbar: ^2.1.1
  material_floating_search_bar_2: ^0.5.0
  provider: ^6.1.4
  implicitly_animated_reorderable_list_2: ^0.6.0
  material_design_icons_flutter: ^7.0.7296
  anim_search_bar: ^2.0.3
  html: ^0.15.5+1
  universal_html: ^2.2.4
  http: ^1.3.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  # - assets/icons/google-fill.svg
  # - assets/icons/facebook-fill.svg
  # - assets/icons/apple-fill.svg
