name: gdgdoc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  blobs: ^2.0.0
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^8.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  simple_animations: ^5.1.0
  simple_gradient_text: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  # - assets/icons/google-fill.svg
  # - assets/icons/facebook-fill.svg
  # - assets/icons/apple-fill.svg
